---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                CM2b1PDYvC8E:
                    host: '8023'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            gymLNfJo0EIs:
                source: ~/src/sites/
                target: /var/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        0dAhZtJOJWYx:
            servername: vagrant
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        1W85rWZVonuP:
            servername: erdem.com.host
            serveraliases:
                - www.erdem.com.host
            docroot: /var/www/erdem.com/build
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            engine: ''
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        yhu4OWx2fBjB:
            servername: wednesday-sample.host
            serveraliases:
                - www.wednesday-sample.host
            docroot: /var/www/wednesday-sample/build/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            engine: ''
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        Y6EqW5KoSI6a:
            servername: dbv.wednesday-sample.host
            docroot: /var/www/wednesday-sample/dbv
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        ToSmRkfH2KJq:
            servername: kentandcurwen.com.host
            serveraliases:
                - kentcurwen.dev
            docroot: /var/www/kentandcurwen.com/deploy/build
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        pbsuLwI2hu4c:
            servername: frame-denim.com.host
            docroot: /var/www/frame-denim.com/deploy/build
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        aqeRIoCdYir5:
            servername: wednesdayagency.com.host
            docroot: /var/www/wednesdayagency.com/deploy
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        JdP1mqf2QmSx:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            location: .php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: ''
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        upload_max_filesize: 32M
        post_max_size: 32M
    timezone: Europe/London
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    root_password: M3rcr3d1
    adminer: '1'
    databases:
        zSd36Jop9CJJ:
            grant:
                - ALL
            name: wednesdayagency.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/saturday-group.com/sql/schema.sql
        U8uT4Etx0xtw:
            grant:
                - ALL
            name: saturday-group.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/saturday-group.com/sql/schema.sql
        qBA9tOCPCBW0:
            grant:
                - ALL
            name: erdem.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/erdem.com/sql/schema.sql
        zIviI7Lv5y46:
            grant:
                - ALL
            name: wednesday-sample
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/wednesday-sample/sql/schema.sql
        ks1lb4eGGhTE:
            grant:
                - ALL
            name: kentandcurwen.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/kentandcurwen.com/sql/schema.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases:
        kVOlx5OoCIkj:
            name: cookadlib
            user: cookadlib
            password: cookadlib
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '0'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true

