---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: null
        memory: '512'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                EicvqCxzh8R7:
                    host: '8023'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            jBi4Yz5LdGAz:
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        ogCw0yffxSEF:
            servername: vagrant
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment:
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        TtU0LBp7vL6i:
            servername: erdem.com.host
            serveraliases:
                - www.erdem.com.host
            docroot: /var/www/erdem.com/build
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment:
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        BO5zqF3xyepz:
            servername: wednesday-sample.host
            serveraliases:
                - www.wednesday-sample.host
            docroot: /var/www/wednesday-sample/build/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment:
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        UeO8Gc6N06cp:
            servername: dbv.wednesday-sample.host
            docroot: /var/www/wednesday-sample/dbv
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment:
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        SQQ4THm6w3Fb:
            servername: kentandcurwen.com.host
            docroot: /var/www/kentandcurwen.com/deploy/build
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment:
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        hW2ixuLgoRta:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/London
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: '123'
    phpmyadmin: '1'
    adminer: '1'
    databases:
        Auyov3gyVBqQ:
            grant:
                - ALL
            name: wednesdayagency.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/saturday-group.com/sql/schema.sql
        iK22EUR72koK:
            grant:
                - ALL
            name: saturday-group.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/saturday-group.com/sql/schema.sql
        32KDjtixYKsy:
            grant:
                - ALL
            name: erdem.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/erdem.com/sql/schema.sql
        QzJy7BEvvmvD:
            grant:
                - ALL
            name: wednesday-sample
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/wednesday-sample/sql/schema.sql
        OpWxYgRs2Hex:
            grant:
                - ALL
            name: kentandcurwen.com
            host: localhost
            user: wednesday
            password: wednesday
            sql_file: /var/www/kentandcurwen.com/sql/schema.sql
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases:
        hkavkjdLpYui:
            name: cookadlib
            user: cookadlib
            password: cookadlib
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

